### PR TITLE
Renames testRunner to multipleTestExecutionsRunner and clean env befo…

### PR DESCRIPTION
**Pull request by jeremy-then**
…re each test execution

### CODE REVIEW

**Review by marcos-iov — APPROVED** [review]

**Review by nathanieliov — APPROVED** [review]

**Comment by jeremy-then** [comment]
pipeline:run

**Comment by jeremy-then** [comment]
pipeline:run

**Comment by jeremy-then** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Pull request closed without merging**
