### PR TITLE
Update pipeline.conf to use version 6.3.0.0

### PR DESCRIPTION
**Pull request by marcos-iov**

### CODE REVIEW

**Review by wilmerrootstock — APPROVED** [review]
LGTM!

**Review by apancorb — APPROVED** [review]

**Review by nathanieliov — APPROVED** [review]

**Review by julia-zack — APPROVED** [review]

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
